theme: jekyll-theme-slate

title: Homepage of Mariano Rodríguez
author: Mariano Rodríguez
email: mariano.rodriguez@cmla.ens-cachan.fr
description: This is the public webpage of Mariano Rodríguez Guerra
baseurl: ""
github_username:  rdguez-mariano
linkedin_username:  rdguez-mariano

