theme: jekyll-theme-slate

title: Mariano Rodríguez
author: Mariano Rodríguez
email: rdguez.mariano@gmail.com
description: Professional website of Mariano Rodríguez Guerra, Mathematician and Computer Scientist.
baseurl: ""
github_username:  rdguez-mariano
linkedin_username:  rdguez-mariano
